Implement update function
arabian9ts/sweeTest pull request #41
Opened 2019-10-09 11:07 UTC by tsubasa9647

implemented update function of Users(Student,Assistant and Teacher)

2019-10-10 02:35 UTC, arabian9ts requested changes
レビューした！

2019-10-10 02:35 UTC, arabian9ts commented on .vscode/settings.json
> +}
[must]このファイルはignoreに追加して削除しておいて

2019-10-10 02:35 UTC, arabian9ts commented on app/adapter/user_dxo.go
> +}
Updateでパスワードを更新する処理を入れるということは、プロフィール更新の際に毎回パスワードを入力しないといけないということ。そして、この処理だとパスワードを打ち間違えた時でも問答無用でパスワードが更新されてしまうから危ない。プロフィール機能の使い勝手が悪くなってしまうから少し工夫した方が良いかも。

2019-10-10 02:35 UTC, arabian9ts commented on app/usecase/interactor/user_interactor_test.go
> +		student := fixture.NewCreateStudentInputFormMock()
`NewCreate...`の部分が不自然な繋がりになってるから名前を変更した方がいいかも。
モデルを渡す(今回はフォームで渡すけど同じ)場合は、Validなものを渡すのかInvalidなものを渡すのかでテストの表現力を上げることができる。

例えば、Validなものを使ったテストはOKであることを期待するテストを書くし、Invalidなものを使ったテストはNGであることを期待するテストを書く。この対応があると、他の開発者が読みやすいコードになる。

2019-10-10 02:35 UTC, arabian9ts commented on app/usecase/interactor/user_interactor_test.go
> +	})
以降のテストでは、`assert.Equal(t, outputForm.Updated, expected)`の形式で書かれているけど、ここだけ構造体のまま比較しているのは何か意図がある？

2019-10-10 02:35 UTC, arabian9ts commented on app/usecase/port/user_output.go
> +	UpdateUserOutput
Updateの追加で、WriteとUpdateが重複するようになっちゃったね。Write -> Create, Read -> Getなどに対応を直しておこう

2019-10-10 09:54 UTC, tsubasa9647 commented on .vscode/settings.json
> +}
24942396ac949c9b036e36d322553bb0c3569564

2019-10-10 10:46 UTC, tsubasa9647 commented on app/usecase/port/user_output.go
> +	UpdateUserOutput
a1da521172cf00b5a9099756ff1294778fb8fa44

2019-10-10 10:46 UTC, tsubasa9647 commented on app/usecase/interactor/user_interactor_test.go
> +		student := fixture.NewCreateStudentInputFormMock()
c8ac62326e64a546621efc40223bb236df8d92f0

2019-10-10 10:47 UTC, tsubasa9647 commented on app/usecase/interactor/user_interactor_test.go
> +	})
c8ac62326e64a546621efc40223bb236df8d92f0

2019-10-10 10:49 UTC, tsubasa9647 commented on .vscode/settings.json
> +}
24942396ac949c9b036e36d322553bb0c3569564

2019-10-10 11:02 UTC, tsubasa9647 commented on app/usecase/port/user_output.go
> +	UpdateUserOutput
bb9cd2734e194c99994bc48b362c2df692800bc3

2019-10-10 11:03 UTC, tsubasa9647 commented on app/usecase/interactor/user_interactor_test.go
> +	})
d2d1f44a27597392f528ec2d52362eff8a22aefd

2019-10-10 11:04 UTC, tsubasa9647 commented on app/usecase/interactor/user_interactor_test.go
> +		student := fixture.NewCreateStudentInputFormMock()
3ebdb64d53d6cc9937bf377280ec1cc82126c43f

2019-10-10 11:04 UTC, tsubasa9647 commented on app/adapter/user_dxo.go
> +}
d2d1f44a27597392f528ec2d52362eff8a22aefd

2019-10-10 11:04 UTC, tsubasa9647 commented on .vscode/settings.json
> +}
bfb27e16ea0c954f165dc50a94cf65001d96159c

2019-10-10 11:05 UTC, tsubasa9647 commented on app/usecase/interactor/user_interactor_test.go
> +		student := fixture.NewCreateStudentInputFormMock()
109095cb7fcf7f019c2a5e59ebefdcad3a514225

2019-10-12 09:17 UTC, arabian9ts commented on .vscode/settings.json
> +}
多分、貼るべきコミットはこっちだね 24942396ac949c9b036e36d322553bb0c3569564
今貼ってあるコミットはrebaseしたものだと思うけど、コミットメッセージが長くなっちゃってるから短めにしておいて

2019-10-12 09:17 UTC, arabian9ts commented on .vscode/settings.json
> +}
あと、.gitignoreの行末に空行を入れておいて

2019-10-12 09:19 UTC, arabian9ts commented on app/usecase/interactor/user_interactor_test.go
> +		student := fixture.NewCreateStudentInputFormMock()
Invalidの係り受け的に、`NewInvalidCreateStudentInputForm`の方がいいかも

2019-10-12 09:22 UTC, arabian9ts commented on app/usecase/port/user_output.go
> +	UpdateUserOutput
もともとあった`UserReadOutput`とかの名前が良くなかったんだけど、動詞から始まる方が自然だね
`GetUserOutput`とかにしよう

2019-10-14 10:29 UTC, tsubasa9647 commented on app/usecase/port/user_output.go
> +	UpdateUserOutput
02e7dd5

2019-10-14 10:47 UTC, tsubasa9647 commented on app/usecase/interactor/user_interactor_test.go
> +		student := fixture.NewCreateStudentInputFormMock()
69495c1

2019-10-31 08:27 UTC, arabian9ts approved these changes

2019-10-31 08:29 UTC, merged