implement participate function
arabian9ts/sweeTest pull request #47
Opened 2019-11-12 13:59 UTC by tsubasa9647

講義に参加と退出まで実装してます。

2019-11-27 06:43 UTC, arabian9ts requested changes
レビューした！

2019-11-27 06:43 UTC, arabian9ts commented on app/dto/participation_form.go
> +}
この辺りgo fmtがかかってなさそう

2019-11-27 06:43 UTC, arabian9ts commented on app/dto/participation_form.go
> +}
別ブランチでは作成、更新、削除のレスポンスは対象リソースになってるから、ここも変更しておいたほうがいいかも。

2019-11-27 06:43 UTC, arabian9ts commented on app/interface/controllers/partcipated_lecture_controller.go
> +	"strconv"
```
"strconv"

"github.com/arabian9ts/sweeTest/app/usecase/interactor"
"github.com/arabian9ts/sweeTest/app/usecase/port"
"github.com/arabian9ts/sweeTest/app/usecase/repository"
"github.com/arabian9ts/sweeTest/app/validator"
```
が良いね

2019-11-27 06:43 UTC, arabian9ts commented on app/interface/controllers/partcipated_lecture_controller.go
> +func NewParticipatedLectureController(repository repository.LectureRepository, output port.LectureOutput, validator validator.Validation) (*ParticipatedLectureController, error) {
ParticipatedLectureだと、主格がないから"参加されている講義"と捉えられそうだね。
能動的に読ませるためにはParticipatingLecturesの方が良さそう。Lectureも複数形で取得するなら複数形で。

2019-11-27 06:43 UTC, arabian9ts commented on app/interface/controllers/partcipated_lecture_controller.go
> +	}
要所要所に空行が欲しいね。
```go
// 1つ目の事柄に対する操作と検証
result1, err := doSomething()
if err != nil {
    return err
}

// 2つ目の事柄に対する操作と検証
result2, err := doAnother()
if err != nil {
    return err
}
```
みたいに、チェック項目ごとに間に空行が欲しい

2019-11-27 06:43 UTC, arabian9ts commented on app/interface/database/lecture_repository.go
> +	rows, err := repo.SqlHandler.Query("select lectures.* from lectures inner join students_lectures on students_lectures.lecture_id = lectures.id where student_id = ? limit ? offset ?;",
クエリ末尾の`;`はなくても良さそうだね

2019-11-27 06:43 UTC, arabian9ts commented on app/interface/database/participation_repository.go
> +
ここの空行は消しておこう

2019-11-27 06:43 UTC, arabian9ts commented on app/interface/database/user_repository.go
> +func (repo *UserRepository) GetParticipatedStudents(lectureID int64, limit int, offset int) (students []*model.Student, err error) {
学生側から参加している講義を取得する関数は、`GetParticipatedLecturesOfStudent`だから、どちらかに統一した方がいいね。

2019-11-27 06:43 UTC, arabian9ts commented on app/interface/database/user_repository.go
> +	students = []*model.Student{}
modelにStudentsって型作ってなかったっけ？

2019-11-28 02:23 UTC, tsubasa9647 commented on app/dto/participation_form.go
> +}
4871adf

2019-11-28 02:25 UTC, tsubasa9647 commented on app/interface/controllers/partcipated_lecture_controller.go
> +	"strconv"
df51302

2019-11-28 02:42 UTC, tsubasa9647 commented on app/interface/controllers/partcipated_lecture_controller.go
> +func NewParticipatedLectureController(repository repository.LectureRepository, output port.LectureOutput, validator validator.Validation) (*ParticipatedLectureController, error) {
d598e71

2019-11-28 02:45 UTC, tsubasa9647 commented on app/interface/controllers/partcipated_lecture_controller.go
> +	}
fd84555

2019-11-28 02:48 UTC, tsubasa9647 commented on app/interface/database/lecture_repository.go
> +	rows, err := repo.SqlHandler.Query("select lectures.* from lectures inner join students_lectures on students_lectures.lecture_id = lectures.id where student_id = ? limit ? offset ?;",
18b3e52

2019-11-28 02:50 UTC, tsubasa9647 commented on app/interface/database/user_repository.go
> +func (repo *UserRepository) GetParticipatedStudents(lectureID int64, limit int, offset int) (students []*model.Student, err error) {
f4b5bec

2019-11-28 02:51 UTC, tsubasa9647 commented on app/interface/database/participation_repository.go
> +
f4b5bec

2019-11-28 03:36 UTC, tsubasa9647 commented on app/interface/database/user_repository.go
> +	students = []*model.Student{}
4191271

2019-11-28 07:58 UTC, tsubasa9647 commented on app/interface/database/user_repository.go
> +func (repo *UserRepository) GetParticipatedStudents(lectureID int64, limit int, offset int) (students []*model.Student, err error) {
5cf72be

2019-11-28 08:32 UTC, tsubasa9647 commented on app/dto/participation_form.go
> +}
b454e5a

2019-11-28 08:39 UTC, arabian9ts requested changes

2019-11-28 08:39 UTC, arabian9ts commented on app/interface/controllers/participants_controller.go
> +	if err != nil {
offsetの前に空行が欲しいかな

2019-11-28 08:39 UTC, arabian9ts commented on app/interface/controllers/participants_controller.go
> +	if err != nil {
offsetの前に空行

2019-11-28 08:39 UTC, arabian9ts commented on app/interface/controllers/participants_controller.go
> +	offset, err := strconv.Atoi(ctx.Query("offset"))
offsetの前に空行

2019-11-28 08:39 UTC, arabian9ts commented on app/interface/controllers/participation_controller.go
> +}
go fmtで最後に空行が入るはずだからかけておいて

2019-11-28 11:13 UTC, tsubasa9647 commented on app/interface/controllers/participants_controller.go
> +	if err != nil {
73cb80a

2019-11-28 11:13 UTC, tsubasa9647 commented on app/interface/controllers/participants_controller.go
> +	if err != nil {
73cb80a

2019-11-28 11:13 UTC, tsubasa9647 commented on app/interface/controllers/participants_controller.go
> +	offset, err := strconv.Atoi(ctx.Query("offset"))
73cb80a

2019-11-28 11:14 UTC, tsubasa9647 commented on app/interface/controllers/participation_controller.go
> +}
73cb80a

2019-11-28 11:28 UTC, arabian9ts approved these changes

2019-11-28 11:33 UTC, merged