modify output response
arabian9ts/sweeTest pull request #48
Opened 2019-12-01 15:35 UTC by tsubasa9647

2019-12-03 03:26 UTC, arabian9ts requested changes

2019-12-03 03:26 UTC, arabian9ts commented on app/dto/help_form.go
> +	Contents  string `validate:"required,lte1000" json:"contents"`
go fmtかけよう

2019-12-03 03:26 UTC, arabian9ts commented on app/dto/user_form.go
> +	Password  string    `validate:"required,lte=100" json:"password"`
jsonタグはjsonタグとして揃えた方がきれいだね  
validateとjson入れ替えよう

2019-12-03 03:26 UTC, arabian9ts commented on app/dto/user_form.go
> +	Password  string    `validate:"required,lte=100" json:"password"`
こっちも、jsonとvalidateの順序を変えよう

2019-12-03 03:26 UTC, arabian9ts commented on app/dto/user_form.go
> +	Password  string    `validate:"required,lte=100" json:"password"`
こっちも

2019-12-03 03:26 UTC, arabian9ts commented on app/dto/user_form.go
> +	Password  string    `validate:"required,lte=100" json:"password"`
こっちも

2019-12-03 03:26 UTC, arabian9ts commented on app/interface/controllers/helps_controller.go
> +	fmt.Println(lectureID)
デバッグログは消そう

2019-12-03 09:12 UTC, tsubasa9647 commented on app/dto/user_form.go
> +	Password  string    `validate:"required,lte=100" json:"password"`
a943747

2019-12-03 09:12 UTC, tsubasa9647 commented on app/dto/user_form.go
> +	Password  string    `validate:"required,lte=100" json:"password"`
a943747

2019-12-03 09:12 UTC, tsubasa9647 commented on app/dto/user_form.go
> +	Password  string    `validate:"required,lte=100" json:"password"`
a943747

2019-12-03 09:12 UTC, tsubasa9647 commented on app/dto/user_form.go
> +	Password  string    `validate:"required,lte=100" json:"password"`
a943747

2019-12-03 09:12 UTC, tsubasa9647 commented on app/dto/help_form.go
> +	Contents  string `validate:"required,lte1000" json:"contents"`
a943747

2019-12-03 09:12 UTC, tsubasa9647 commented on app/interface/controllers/helps_controller.go
> +	fmt.Println(lectureID)
a943747

2019-12-04 01:43 UTC, tsubasa9647 commented
4d0a545

2019-12-05 09:26 UTC, merged