implement controller
arabian9ts/sweeTest pull request #53
Opened 2019-12-09 16:37 UTC by tsubasa9647

2019-12-10 00:17 UTC, arabian9ts requested changes

2019-12-10 00:17 UTC, arabian9ts commented on app/interface/controllers/classes_controller.go
> +	id, err := strconv.Atoi(ctx.Param("class_id"))
`getClassId(ctx Context)`を作ってもいいかも

2019-12-10 00:18 UTC, arabian9ts commented on app/interface/controllers/classes_controller.go
> +	id, err := strconv.Atoi(ctx.Param("class_id"))
classに紐づく課題ではしばしば`class_id`を取得することになるからね

2019-12-10 02:21 UTC, tsubasa9647 commented on app/interface/controllers/classes_controller.go
> +	id, err := strconv.Atoi(ctx.Param("class_id"))
一応作ってますよー！
下のほうに

2019-12-10 11:40 UTC, arabian9ts commented on app/interface/controllers/classes_controller.go
> +	id, err := strconv.Atoi(ctx.Param("class_id"))
なんで使ってないんｗ

2019-12-10 13:26 UTC, tsubasa9647 commented on app/interface/controllers/classes_controller.go
> +	id, err := strconv.Atoi(ctx.Param("class_id"))
なるほどここで使っててことですね（笑）

2019-12-10 13:34 UTC, tsubasa9647 commented on app/interface/controllers/classes_controller.go
> +	id, err := strconv.Atoi(ctx.Param("class_id"))
d628cfd

2019-12-12 00:02 UTC, arabian9ts requested changes

2019-12-12 00:02 UTC, arabian9ts commented on app/interface/controllers/parameter.go
> +	if err != nil {
他の`getXXXID`がどうなってたかはあんまり覚えてないけど、パスパラメータが指定されていない場合はcontrollerで弾いてしまいたいから、errも返した方がいいかな。アクション側でerrがnilじゃなければreturnで。

2019-12-12 01:58 UTC, tsubasa9647 commented on app/interface/controllers/parameter.go
> +	if err != nil {
ab29c3e

2019-12-12 15:38 UTC, tsubasa9647 commented on app/interface/controllers/parameter.go
> +	if err != nil {
1a604b5

2019-12-12 15:55 UTC, tsubasa9647 commented on app/interface/controllers/parameter.go
> +	if err != nil {
5c4e81c

2019-12-12 16:05 UTC, tsubasa9647 commented on app/interface/controllers/parameter.go
> +	if err != nil {
6fb5a31

2019-12-12 16:07 UTC, merged